baseURL  =  "https://immmmm.com"
languageCode = "zh-CN"
defaultContentLanguage = "zh-CN"
title  =  "木木木木木"
theme  =  "hello-friend"
summaryLength = 140
hasCJKLanguage = true
paginate =  20
rssLimit = 5

[permalinks]
  posts = "/:filename/"

[menu]
  [[menu.main]]
	name="首页"
	url="/"
	weight="1"
  [[menu.main]]
	name="关于"
	url="/about"
	weight="2"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  logoText = "hello friend"

  # DateFormatList = "2006-01-02 15:04"
  # DateFormatSingle = "2006-01-02 15:04"

  ReadMore = "阅读全文"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  # <domain>/atom.xml
  home = ["Atom", "HTML"]

[outputFormats.Atom]
  mediatype = "application/rss"
  baseName = "atom"

[params.valine]
	enable = true
    appId = 'm6rxiyixBDG25mYPEPapQpnR-MdYXbMMI'
    appKey = 'WMokwNAwh9noJ4XeUjVBjsCt'
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true